# Generated by Django 5.0.6 on 2024-07-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
